export const AUTHORIZE_SUCCESS = 'AUTHORIZE_SUCCESS';
export const AUTHORIZE_ERROR = 'AUTHORIZE_ERROR';

export const WHOAMI_SUCCESS = 'WHOAMI_SUCCESS';
export const AUTHENTICATE_ERROR = 'WHOAMI_ERROR';