export const GET_COMPLETED_TASKS_LIST_SUCCESS = 'GET_COMPLETED_TASKS_LIST_SUCCESS';
export const GET_CURRENT_TASKS_LIST_SUCCESS = 'GET_CURRENT_TASKS_LIST_SUCCESS';
export const GET_COMPLETED_TASKS_LIST_ERROR = 'GET_COMPLETED_TASKS_LIST_ERROR';
export const GET_CURRENT_TASKS_LIST_ERROR = 'GET_CURRENT_TASKS_LIST_ERROR';

export const ADD_NEW_TASK = 'ADD_NEW_TASK';