export const GET_TASKS_LIST_SUCCESS = 'GET_TASKS_LIST_SUCCESS';
export const GET_TASKS_LIST_ERROR = 'GET_TASKS_LIST_ERROR';

export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const ADD_NEW_TASK_ERROR = 'ADD_NEW_TASK_ERROR';

export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

export const PATCH_TASK_SUCCESS = 'PATCH_TASK_SUCCESS';
export const PATCH_TASK_ERROR = 'PATCH_TASK_ERROR';